import * as stylex from '@stylexjs/stylex'
import { tokens } from '../../tokens/tokens.stylex'

export const styles = stylex.create({
  card: {
    backgroundColor: tokens.colorBg,
    borderRadius: tokens.radiusMd,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: tokens.colorBorderSubtle,
    padding: tokens.spacing6,
    boxShadow: tokens.shadowSm,
    display: 'flex',
    flexDirection: 'column',
    gap: tokens.spacing4,
    fontFamily: tokens.fontFamilyBase,
    position: 'relative',
    color: tokens.colorFg,
    overflow: 'hidden',
  },
  cardEdgeToEdge: {
    padding: 0,
    gap: 0,
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: tokens.spacing4,
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: 'transparent',
    paddingBlockEnd: tokens.spacing2,
  },
  headerEdgeToEdge: {
    paddingBlockStart: tokens.spacing5,
    paddingBlockEnd: tokens.spacing4,
    paddingInline: tokens.spacing6,
  },
  headerDivider: {
    borderBottomColor: tokens.colorBorderSubtle,
  },
  title: {
    fontSize: tokens.fontSizeLg,
    fontWeight: tokens.fontWeightSemibold,
    lineHeight: tokens.lineHeightLg,
    color: tokens.colorFg,
    margin: 0,
  },
  description: {
    fontSize: tokens.fontSizeXs,
    color: tokens.colorFgSubtle,
    marginBlockStart: tokens.spacing1,
  },
  actions: {
    display: 'flex',
    alignItems: 'center',
    gap: tokens.spacing2,
  },
  legend: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: tokens.spacing3,
    fontSize: tokens.fontSizeSm,
    color: tokens.colorFgSubtle,
    lineHeight: tokens.lineHeightSm,
  },
  legendItem: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: tokens.spacing2,
  },
  legendDot: {
    width: '10px',
    height: '10px',
    borderRadius: tokens.radiusFull,
    display: 'inline-block',
    flexShrink: 0,
  },
  legendName: {
    color: tokens.colorFgSubtle,
  },
  legendValue: {
    fontWeight: tokens.fontWeightSemibold,
    color: tokens.colorFg,
    marginInlineStart: tokens.spacing1,
  },
  legendMore: {
    fontWeight: tokens.fontWeightSemibold,
    color: tokens.colorFg,
    fontSize: tokens.fontSizeSm,
  },
  body: {
    position: 'relative',
    minHeight: '260px',
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  bodyEdgeToEdge: {
    minHeight: 'auto',
    display: 'block',
  },
  loadingContainer: {
    position: 'absolute',
    inset: 0,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: tokens.colorBgGlass,
    zIndex: 10,
  },
  emptyContainer: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    gap: tokens.spacing2,
    color: tokens.colorFgSubtle,
    fontSize: tokens.fontSizeSm,
    paddingBlock: tokens.spacing8,
  },
})
