import * as stylex from '@stylexjs/stylex'
import { tokens } from '../../tokens/tokens.stylex'

const fadeIn = stylex.keyframes({
  from: { opacity: 0 },
  to: { opacity: 1 },
})

const scaleIn = stylex.keyframes({
  from: { transform: 'scale(0.96) translateY(-8px)', opacity: 0 },
  to: { transform: 'scale(1) translateY(0)', opacity: 1 },
})

export const styles = stylex.create({
  overlay: {
    position: 'fixed',
    inset: 0,
    zIndex: tokens.zIndexModal,
    backgroundColor: tokens.colorOverlay,
    backdropFilter: 'blur(4px)',
    display: 'flex',
    alignItems: {
      default: 'flex-start',
      '@media (max-width: 640px)': 'center',
    },
    justifyContent: 'center',
    paddingBlockStart: {
      default: '12vh',
      '@media (max-width: 640px)': 0,
    },
    paddingInline: tokens.spacing4,
    animationName: fadeIn,
    animationDuration: '0.2s',
    animationTimingFunction: 'ease-out',
  },
  dialog: {
    backgroundColor: tokens.colorBgElevated,
    boxShadow: tokens.shadowLg,
    borderRadius: tokens.radiusLg,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: tokens.colorBorder,
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    outline: 'none',
    boxSizing: 'border-box',
    animationName: scaleIn,
    animationDuration: '0.2s',
    animationTimingFunction: 'cubic-bezier(0.16, 1, 0.3, 1)',
  },
  sm: {
    maxWidth: '460px',
  },
  md: {
    maxWidth: '580px',
  },
  lg: {
    maxWidth: '700px',
  },
  inputWrapper: {
    display: 'flex',
    alignItems: 'center',
    paddingInline: tokens.spacing4,
    borderBlockEndWidth: '1px',
    borderBlockEndStyle: 'solid',
    borderBlockEndColor: tokens.colorBorderSubtle,
    gap: tokens.spacing3,
    minHeight: '52px',
    boxSizing: 'border-box',
  },
  searchIcon: {
    width: '20px',
    height: '20px',
    color: tokens.colorFgSubtle,
    flexShrink: 0,
  },
  input: {
    flex: 1,
    borderWidth: 0,
    outline: 'none',
    backgroundColor: 'transparent',
    color: tokens.colorFg,
    fontSize: tokens.fontSizeMd,
    lineHeight: tokens.lineHeightMd,
    paddingBlock: tokens.spacing3,
    '::placeholder': {
      color: tokens.colorFgSubtle,
    },
  },
  clearButton: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    borderWidth: 0,
    color: tokens.colorFgSubtle,
    cursor: 'pointer',
    padding: tokens.spacing1,
    borderRadius: tokens.radiusSm,
    ':hover': {
      color: tokens.colorFg,
      backgroundColor: tokens.colorNeutral100,
    },
  },
  kbdEsc: {
    cursor: 'pointer',
  },
  list: {
    maxHeight: '340px',
    overflowY: 'auto',
    padding: tokens.spacing2,
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
    boxSizing: 'border-box',
    outline: 'none',
  },
  section: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
  },
  sectionHeader: {
    fontSize: tokens.fontSizeXs,
    fontWeight: tokens.fontWeightSemibold,
    color: tokens.colorFgSubtle,
    paddingBlock: tokens.spacing2,
    paddingInline: tokens.spacing3,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    userSelect: 'none',
  },
  item: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBlock: tokens.spacing2,
    paddingInline: tokens.spacing3,
    borderRadius: tokens.radiusSm,
    color: tokens.colorFg,
    fontSize: tokens.fontSizeSm,
    cursor: 'pointer',
    userSelect: 'none',
    outline: 'none',
    textDecoration: 'none',
    transition: 'background-color 0.12s ease, color 0.12s ease',
    gap: tokens.spacing3,
  },
  itemContent: {
    display: 'flex',
    alignItems: 'center',
    gap: tokens.spacing3,
    flex: 1,
    minWidth: 0,
  },
  itemIcon: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: tokens.colorFgSubtle,
    flexShrink: 0,
    width: '18px',
    height: '18px',
  },
  itemTextWrapper: {
    display: 'flex',
    flexDirection: 'column',
    minWidth: 0,
  },
  itemLabel: {
    fontWeight: tokens.fontWeightMedium,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  itemDescription: {
    fontSize: tokens.fontSizeXs,
    color: tokens.colorFgSubtle,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  itemMeta: {
    display: 'flex',
    alignItems: 'center',
    gap: tokens.spacing2,
    flexShrink: 0,
  },
  itemHovered: {
    backgroundColor: tokens.colorNeutral100,
  },
  itemActive: {
    backgroundColor: tokens.colorPrimary100,
    color: tokens.colorPrimary800,
  },
  itemDisabled: {
    opacity: 0.4,
    cursor: 'not-allowed',
    pointerEvents: 'none',
  },
  empty: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    paddingBlock: tokens.spacing8,
    paddingInline: tokens.spacing4,
    color: tokens.colorFgSubtle,
    fontSize: tokens.fontSizeSm,
    textAlign: 'center',
    gap: tokens.spacing2,
  },
  footer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: tokens.spacing4,
    paddingBlock: tokens.spacing2,
    paddingInline: tokens.spacing4,
    borderBlockStartWidth: '1px',
    borderBlockStartStyle: 'solid',
    borderBlockStartColor: tokens.colorBorderSubtle,
    backgroundColor: tokens.colorBgSubtle,
    fontSize: tokens.fontSizeXs,
    color: tokens.colorFgSubtle,
  },
  footerKeyGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: tokens.spacing1,
  },
})
