import * as stylex from '@stylexjs/stylex'
import { tokens } from '../../tokens/tokens.stylex'

export const styles = stylex.create({
  container: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    gap: tokens.spacing3,
    padding: tokens.spacing5,
    borderRadius: tokens.radiusLg,
    fontFamily: tokens.fontFamilyBase,
    color: tokens.colorFg,
    minWidth: '160px',
    flex: 1,
    height: '100%',
    boxSizing: 'border-box',
    transitionProperty: 'background-color, border-color, box-shadow',
    transitionDuration: '0.15s',
  },
  variantDefault: {
    backgroundColor: tokens.colorBg,
    borderColor: tokens.colorBorderSubtle,
    borderWidth: '1px',
    borderStyle: 'solid',
  },
  variantFlat: {
    backgroundColor: tokens.colorBgSubtle,
    borderColor: 'transparent',
    borderWidth: '1px',
    borderStyle: 'solid',
  },
  variantGlass: {
    backgroundColor: tokens.colorBgGlass,
    borderColor: tokens.colorBorderGlass,
    borderWidth: '1px',
    borderStyle: 'solid',
    backdropFilter: 'blur(24px)',
    WebkitBackdropFilter: 'blur(24px)',
    boxShadow: tokens.shadowSm,
  },
  variantElevated: {
    backgroundColor: tokens.colorBgElevated,
    borderColor: tokens.colorBorderSubtle,
    borderWidth: '1px',
    borderStyle: 'solid',
    boxShadow: tokens.shadowSm,
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: tokens.spacing2,
  },
  label: {
    fontSize: tokens.fontSizeXs,
    fontWeight: tokens.fontWeightMedium,
    color: tokens.colorFgSubtle,
    letterSpacing: '0.02em',
  },
  icon: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: tokens.colorFgSubtle,
    flexShrink: 0,
  },
  body: {
    display: 'flex',
    flexDirection: 'column',
    gap: tokens.spacing1,
    flexGrow: 1,
  },
  value: {
    fontSize: tokens.fontSize3xl,
    fontWeight: tokens.fontWeightBold,
    lineHeight: tokens.lineHeight3xl,
    color: tokens.colorFg,
  },
  description: {
    fontSize: tokens.fontSizeXs,
    color: tokens.colorFgSubtle,
  },
  footer: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: tokens.spacing2,
    fontSize: tokens.fontSizeXs,
  },
  trendBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: tokens.spacing1,
    fontWeight: tokens.fontWeightSemibold,
    paddingBlock: '2px',
    paddingInline: tokens.spacing2,
    borderRadius: tokens.radiusFull,
    fontSize: tokens.fontSizeXs,
    lineHeight: tokens.lineHeightXs,
  },
  trendUp: {
    backgroundColor: tokens.colorSuccess300,
    color: tokens.colorSuccess700,
  },
  trendDown: {
    backgroundColor: tokens.colorError300,
    color: tokens.colorError700,
  },
  trendNeutral: {
    backgroundColor: tokens.colorNeutral200,
    color: tokens.colorNeutral700,
  },
  trendText: {
    color: tokens.colorFgSubtle,
  },
})
