import * as stylex from '@stylexjs/stylex'
import { tokens } from '../../tokens/tokens.stylex'

export const styles = stylex.create({
  calendar: {
    display: 'inline-flex',
    flexDirection: 'column',
    width: 'fit-content',
    backgroundColor: tokens.colorBgElevated,
    borderRadius: tokens.radiusMd,
    padding: tokens.spacing3,
    userSelect: 'none',
    boxSizing: 'border-box',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBlockEnd: tokens.spacing2,
    gap: tokens.spacing2,
  },
  heading: {
    margin: 0,
    fontSize: tokens.fontSizeSm,
    fontWeight: tokens.fontWeightSemibold,
    color: tokens.colorFg,
    textAlign: 'center',
    flex: 1,
  },
  navButton: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: tokens.spacing7,
    height: tokens.spacing7,
    borderRadius: tokens.radiusSm,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: tokens.colorBorderSubtle,
    backgroundColor: 'transparent',
    color: tokens.colorFg,
    cursor: 'pointer',
    outline: 'none',
    transition: 'background-color 0.15s ease, border-color 0.15s ease',
  },
  navButtonHover: {
    backgroundColor: tokens.colorNeutral100,
    borderColor: tokens.colorBorder,
  },
  navButtonPressed: {
    backgroundColor: tokens.colorNeutral200,
  },
  navButtonDisabled: {
    opacity: 0.4,
    cursor: 'not-allowed',
    pointerEvents: 'none',
  },
  navButtonFocused: {
    borderColor: tokens.colorBorderFocus,
    boxShadow: `0 0 0 2px ${tokens.colorBorderFocus}`,
  },
  navIcon: {
    width: '16px',
    height: '16px',
  },
  grid: {
    borderCollapse: 'collapse',
    width: '100%',
  },
  gridHeaderCell: {
    fontSize: tokens.fontSizeXs,
    fontWeight: tokens.fontWeightMedium,
    color: tokens.colorFgSubtle,
    textAlign: 'center',
    paddingBlock: tokens.spacing1,
    width: '36px',
  },
  gridBody: {},
  gridRow: {
    display: 'table-row',
  },
  cellContainer: {
    paddingBlock: '2px',
    paddingInline: 0,
    textAlign: 'center',
  },
  cell: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '34px',
    height: '34px',
    borderRadius: tokens.radiusSm,
    fontSize: tokens.fontSizeSm,
    lineHeight: tokens.lineHeightSm,
    color: tokens.colorFg,
    backgroundColor: 'transparent',
    cursor: 'pointer',
    outline: 'none',
    boxSizing: 'border-box',
    transition: 'background-color 0.12s ease, color 0.12s ease',
  },
  cellHovered: {
    backgroundColor: tokens.colorNeutral100,
  },
  cellFocused: {
    outline: 'none',
    boxShadow: `0 0 0 2px ${tokens.colorBorderFocus}`,
  },
  cellSelected: {
    backgroundColor: tokens.colorPrimary500,
    color: tokens.colorFgOnPrimary,
    fontWeight: tokens.fontWeightSemibold,
  },
  cellSelectionStart: {
    backgroundColor: tokens.colorPrimary500,
    color: tokens.colorFgOnPrimary,
    borderStartStartRadius: tokens.radiusSm,
    borderEndStartRadius: tokens.radiusSm,
    borderStartEndRadius: 0,
    borderEndEndRadius: 0,
    fontWeight: tokens.fontWeightSemibold,
  },
  cellSelectionEnd: {
    backgroundColor: tokens.colorPrimary500,
    color: tokens.colorFgOnPrimary,
    borderStartEndRadius: tokens.radiusSm,
    borderEndEndRadius: tokens.radiusSm,
    borderStartStartRadius: 0,
    borderEndStartRadius: 0,
    fontWeight: tokens.fontWeightSemibold,
  },
  cellRangeSelection: {
    backgroundColor: tokens.colorPrimary100,
    color: tokens.colorPrimary800,
    borderRadius: 0,
  },
  cellToday: {
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: tokens.colorPrimary500,
    fontWeight: tokens.fontWeightBold,
  },
  cellOutsideMonth: {
    color: tokens.colorNeutral400,
    opacity: 0.5,
  },
  cellDisabled: {
    color: tokens.colorNeutral300,
    cursor: 'not-allowed',
    pointerEvents: 'none',
    opacity: 0.4,
  },
  cellUnavailable: {
    color: tokens.colorNeutral400,
    textDecoration: 'line-through',
    cursor: 'not-allowed',
  },
  cellInvalid: {
    backgroundColor: tokens.colorError500,
    color: tokens.colorFgOnPrimary,
  },
})
