import * as stylex from '@stylexjs/stylex'
import { tokens } from '../../tokens/tokens.stylex'

const caretBlink = stylex.keyframes({
  '0%, 100%': { opacity: 1 },
  '50%': { opacity: 0 },
})

export const styles = stylex.create({
  container: {
    display: 'flex',
    flexDirection: 'column',
    gap: tokens.spacing2,
    width: '100%',
  },
  
  // Style for the container generated by input-otp wrapper
  otpContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: tokens.spacing2,
    outline: 'none',
    userSelect: 'none',
  },

  group: {
    display: 'flex',
    alignItems: 'center',
    gap: tokens.spacing2,
  },

  slot: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '3rem', // 48px
    height: '3rem', // 48px
    fontFamily: tokens.fontFamilyBase,
    fontSize: tokens.fontSizeLg,
    fontWeight: tokens.fontWeightMedium,
    color: tokens.colorFg,
    backgroundColor: tokens.colorBg,
    borderColor: tokens.colorBorder,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderRadius: tokens.radiusMd,
    boxShadow: tokens.shadowSm,
    transitionProperty: 'border-color, box-shadow',
    transitionDuration: '0.15s',
    transitionTimingFunction: 'ease-in-out',
    userSelect: 'none',

    ':hover': {
      borderColor: tokens.colorNeutral400,
    },
  },

  slotActive: {
    zIndex: 10,
    borderColor: tokens.colorBorderFocus,
    boxShadow: `0 0 0 2px ${tokens.colorBorderFocus}`,
  },

  slotInvalid: {
    borderColor: tokens.colorError500,
    boxShadow: `0 0 0 1px ${tokens.colorError500}`,
    ':hover': {
      borderColor: tokens.colorError600,
    },
  },

  slotDisabled: {
    opacity: 0.5,
    backgroundColor: tokens.colorBgSubtle,
    cursor: 'not-allowed',
    boxShadow: 'none',
    ':hover': {
      borderColor: tokens.colorBorder,
    },
  },

  caretContainer: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    pointerEvents: 'none',
  },

  caret: {
    width: '2px',
    height: '1.25rem', // 20px
    backgroundColor: tokens.colorFg,
    animationName: caretBlink,
    animationDuration: '1s',
    animationIterationCount: 'infinite',
    animationTimingFunction: 'step-end',
  },

  separator: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: tokens.colorFgSubtle,
    paddingInline: tokens.spacing1,
  },

  separatorDot: {
    width: '6px',
    height: '6px',
    borderRadius: tokens.radiusFull,
    backgroundColor: tokens.colorBorder,
  },
})
