import * as stylex from '@stylexjs/stylex'
import { tokens } from '../../tokens/tokens.stylex'

export const styles = stylex.create({
  container: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    backgroundColor: tokens.colorBg,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: tokens.colorBorderSubtle,
    borderRadius: tokens.radiusMd,
    overflow: 'hidden',
    boxShadow: tokens.shadowSm,
    fontFamily: tokens.fontFamilyBase,
    color: tokens.colorFg,
  },
  toolbar: {
    display: 'flex',
    flexDirection: 'column',
    gap: tokens.spacing3,
    paddingBlock: tokens.spacing4,
    paddingInline: tokens.spacing4,
    backgroundColor: tokens.colorBgSubtle,
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorBorderSubtle,
  },
  toolbarRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: tokens.spacing3,
    flexWrap: 'wrap',
  },
  titleGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: tokens.spacing2,
  },
  title: {
    fontSize: tokens.fontSizeMd,
    fontWeight: tokens.fontWeightBold,
    color: tokens.colorFg,
    margin: 0,
    letterSpacing: '-0.01em',
  },
  actionsGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: tokens.spacing2,
    flexWrap: 'wrap',
  },
  controlsRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: tokens.spacing3,
    flexWrap: 'wrap',
  },
  searchContainer: {
    flex: 1,
    minWidth: '240px',
  },
  filterGroup: {
    flexShrink: 0,
  },
  tableScrollContainer: {
    position: 'relative',
    width: '100%',
    overflowX: 'auto',
    overflowY: 'auto',
    backgroundColor: tokens.colorBg,
    scrollBehavior: 'smooth',
    '@media (prefers-reduced-motion: reduce)': {
      scrollBehavior: 'auto',
    },
  },
  table: {
    borderCollapse: 'collapse',
    width: '100%',
    textAlign: 'start',
    fontFamily:
      'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
    fontSize: tokens.fontSizeXs,
    lineHeight: tokens.lineHeightXs,
    color: tokens.colorFg,
  },
  header: {
    backgroundColor: tokens.colorBgSubtle,
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorBorderSubtle,
    position: 'sticky',
    top: 0,
    zIndex: 1,
  },
  column: {
    paddingBlock: tokens.spacing2,
    paddingInline: tokens.spacing3,
    fontWeight: tokens.fontWeightSemibold,
    color: tokens.colorFgSubtle,
    textAlign: 'start',
    outline: 'none',
    userSelect: 'none',
    ':focus-visible': {
      outlineStyle: 'solid',
      outlineWidth: '2px',
      outlineOffset: '-2px',
      outlineColor: tokens.colorBorderFocus,
    },
  },
  columnCompact: {
    paddingBlock: tokens.spacing1,
    paddingInline: tokens.spacing2,
  },
  columnLineNumber: {
    width: '48px',
    textAlign: 'end',
  },
  columnTimestamp: {
    width: '160px',
  },
  columnLevel: {
    width: '72px',
  },
  columnMessage: {
    width: 'auto',
  },
  columnActions: {
    width: '64px',
    textAlign: 'end',
  },
  body: {
    outline: 'none',
  },
  row: {
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorBorderSubtle,
    backgroundColor: tokens.colorBg,
    outline: 'none',
    cursor: 'pointer',
    transitionProperty: 'background-color',
    transitionDuration: '0.1s',
    '@media (prefers-reduced-motion: reduce)': {
      transitionProperty: 'none',
    },
  },
  rowHovered: {
    backgroundColor: tokens.colorBgSubtle,
  },
  rowSelected: {
    backgroundColor: tokens.colorPrimary50,
  },
  rowFocused: {
    outlineStyle: 'solid',
    outlineWidth: '2px',
    outlineOffset: '-2px',
    outlineColor: tokens.colorBorderFocus,
  },
  rowError: {
    backgroundColor: tokens.colorAlertBgError,
    borderLeftWidth: '2px',
    borderLeftStyle: 'solid',
    borderLeftColor: tokens.colorError500,
  },
  rowWarn: {
    backgroundColor: tokens.colorAlertBgWarning,
    borderLeftWidth: '2px',
    borderLeftStyle: 'solid',
    borderLeftColor: tokens.colorWarning500,
  },
  rowFatal: {
    backgroundColor: tokens.colorAlertBgError,
    borderLeftWidth: '2px',
    borderLeftStyle: 'solid',
    borderLeftColor: tokens.colorError600,
  },
  cell: {
    paddingBlock: tokens.spacing2,
    paddingInline: tokens.spacing3,
    color: 'inherit',
    outline: 'none',
    verticalAlign: 'top',
  },
  cellCompact: {
    paddingBlock: tokens.spacing1,
    paddingInline: tokens.spacing2,
  },
  cellLineNumber: {
    textAlign: 'end',
    color: tokens.colorFgSubtle,
    userSelect: 'none',
    opacity: 0.6,
  },
  cellTimestamp: {
    color: tokens.colorFgSubtle,
    whiteSpace: 'nowrap',
  },
  cellLevel: {
    whiteSpace: 'nowrap',
  },
  cellMessage: {
    color: tokens.colorFg,
  },
  cellActions: {
    textAlign: 'end',
    whiteSpace: 'nowrap',
  },
  cellWrap: {
    wordBreak: 'break-word',
    whiteSpace: 'pre-wrap',
  },
  cellNoWrap: {
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  messageContent: {
    display: 'flex',
    flexDirection: 'column',
    gap: tokens.spacing1,
    minWidth: 0,
  },
  messageContentNoWrap: {
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  messageText: {
    display: 'inline',
    whiteSpace: 'inherit',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  // ── Key-Value Attribute Chips ──────────────────────────────────────────
  attributeList: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: tokens.spacing1,
    marginTop: tokens.spacing1,
  },
  attributeListNoWrap: {
    flexWrap: 'nowrap',
    overflow: 'hidden',
  },
  attributeChip: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: tokens.spacing1,
    paddingBlock: '1px',
    paddingInline: tokens.spacing1,
    fontSize: tokens.fontSizeXs,
    backgroundColor: tokens.colorNeutral100,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: tokens.colorBorderSubtle,
    borderRadius: tokens.radiusSm,
    color: tokens.colorFgSubtle,
    fontFamily:
      'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    lineHeight: tokens.lineHeightXs,
  },
  attributeChipError: {
    backgroundColor: tokens.colorAlertBgError,
    borderColor: tokens.colorAlertBorderError,
  },
  attributeKey: {
    fontWeight: tokens.fontWeightMedium,
    color: tokens.colorFgSubtle,
  },
  attributeKeyError: {
    color: tokens.colorError600,
    fontWeight: tokens.fontWeightSemibold,
  },
  attributeValue: {
    fontWeight: tokens.fontWeightNormal,
    color: tokens.colorFg,
  },
  attributeValueError: {
    color: tokens.colorError600,
    fontWeight: tokens.fontWeightMedium,
  },
  statusSuccess: {
    color: tokens.colorSuccess600,
    fontWeight: tokens.fontWeightBold,
  },
  statusWarn: {
    color: tokens.colorWarning600,
    fontWeight: tokens.fontWeightBold,
  },
  statusError: {
    color: tokens.colorError500,
    fontWeight: tokens.fontWeightBold,
  },
  // ── Inline Inspector Panel ─────────────────────────────────────────────
  inspector: {
    display: 'flex',
    flexDirection: 'column',
    gap: tokens.spacing3,
    paddingBlock: tokens.spacing3,
    paddingInline: tokens.spacing3,
    backgroundColor: tokens.colorBgSubtle,
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: tokens.colorBorderSubtle,
  },
  inspectorHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: tokens.spacing2,
  },
  inspectorTitle: {
    fontSize: tokens.fontSizeSm,
    fontWeight: tokens.fontWeightSemibold,
    color: tokens.colorFg,
    margin: 0,
  },
  inspectorGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: tokens.spacing2,
  },
  inspectorItem: {
    display: 'flex',
    flexDirection: 'column',
    gap: tokens.spacing1,
    paddingBlock: tokens.spacing2,
    paddingInline: tokens.spacing2,
    backgroundColor: tokens.colorBg,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: tokens.colorBorderSubtle,
    borderRadius: tokens.radiusSm,
  },
  inspectorItemKey: {
    fontSize: tokens.fontSizeXs,
    fontWeight: tokens.fontWeightSemibold,
    color: tokens.colorFgSubtle,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  inspectorItemValue: {
    fontSize: tokens.fontSizeXs,
    color: tokens.colorFg,
    fontFamily:
      'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    wordBreak: 'break-all',
  },
  rawCodeBlock: {
    margin: 0,
    paddingBlock: tokens.spacing2,
    paddingInline: tokens.spacing3,
    backgroundColor: tokens.colorBgSubtle,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: tokens.colorBorderSubtle,
    borderRadius: tokens.radiusSm,
    fontSize: tokens.fontSizeXs,
    fontFamily:
      'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    color: tokens.colorFg,
    overflowX: 'auto',
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-all',
  },
  // ── Drawer Inspector Single Line Header & Clean Cards ──────────────────
  drawerHeaderSingleLine: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: tokens.spacing3,
    width: '100%',
  },
  drawerHeaderTitleGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: tokens.spacing2,
    flexWrap: 'wrap',
    minWidth: 0,
  },
  drawerHeaderTimestamp: {
    fontSize: tokens.fontSizeXs,
    color: tokens.colorFgSubtle,
    fontFamily:
      'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
  },
  drawerBodyContent: {
    display: 'flex',
    flexDirection: 'column',
    gap: tokens.spacing3,
  },
  cardHeaderFlex: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: tokens.spacing2,
    width: '100%',
    paddingBlock: tokens.spacing2,
    paddingInline: tokens.spacing3,
  },
  drawerSectionTitle: {
    fontSize: tokens.fontSizeXs,
    fontWeight: tokens.fontWeightBold,
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
    color: tokens.colorFgSubtle,
    margin: 0,
  },
  drawerAttrTable: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
  },
  drawerAttrRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: tokens.spacing2,
    paddingBlock: tokens.spacing2,
    paddingInline: tokens.spacing3,
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorBorderSubtle,
    fontSize: tokens.fontSizeXs,
    ':last-child': {
      borderBottomWidth: 0,
    },
  },
  drawerAttrKey: {
    fontWeight: tokens.fontWeightMedium,
    color: tokens.colorFgSubtle,
    fontFamily:
      'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    flexShrink: 0,
    minWidth: '100px',
  },
  drawerAttrVal: {
    fontFamily:
      'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    color: tokens.colorFg,
    wordBreak: 'break-all',
    textAlign: 'end',
    flex: 1,
  },
  cardBodyFlush: {
    padding: 0,
  },
  drawerFooterWrap: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    gap: tokens.spacing2,
    flexWrap: 'wrap',
  },
  // ── Empty State ────────────────────────────────────────────────────────
  emptyState: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    paddingBlock: tokens.spacing8,
    paddingInline: tokens.spacing4,
    gap: tokens.spacing2,
    color: tokens.colorFgSubtle,
    textAlign: 'center',
  },
  emptyStateText: {
    fontSize: tokens.fontSizeSm,
    fontWeight: tokens.fontWeightMedium,
  },
  // ── Search Highlights ──────────────────────────────────────────────────
  searchHighlight: {
    backgroundColor: tokens.colorPrimary100,
    color: tokens.colorPrimary900,
    borderRadius: tokens.radiusSm,
    paddingInline: tokens.spacing1,
    fontWeight: tokens.fontWeightSemibold,
  },
  // ── Visually Hidden for Screen Readers / Live Regions ─────────────────
  visuallyHidden: {
    position: 'absolute',
    width: '1px',
    height: '1px',
    padding: 0,
    margin: '-1px',
    overflow: 'hidden',
    clip: 'rect(0, 0, 0, 0)',
    whiteSpace: 'nowrap',
    borderWidth: 0,
  },
})

