import * as stylex from '@stylexjs/stylex'
import { tokens } from '../../tokens/tokens.stylex'

export const styles = stylex.create({
  container: {
    display: 'flex',
    flexDirection: 'column',
    gap: tokens.spacing1,
    width: '100%',
  },
  trigger: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    paddingBlock: tokens.spacing2,
    paddingInline: tokens.spacing3,
    borderRadius: tokens.radiusMd,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: tokens.colorBorder,
    backgroundColor: tokens.colorBg,
    color: tokens.colorFg,
    fontFamily: tokens.fontFamilyBase,
    fontSize: tokens.fontSizeMd,
    lineHeight: tokens.lineHeightMd,
    outline: 'none',
    cursor: 'pointer',
    boxShadow: tokens.shadowSm,
    transitionProperty: 'border-color, box-shadow, background-color',
    transitionDuration: '0.15s',
    transitionTimingFunction: 'ease-in-out',
    ':hover': {
      borderColor: tokens.colorNeutral400,
    },
    ':focus-visible': {
      borderColor: tokens.colorBorderFocus,
      boxShadow: `0 0 0 1px ${tokens.colorBorderFocus}`,
    },
  },
  triggerInvalid: {
    borderColor: tokens.colorError500,
    ':focus-visible': {
      borderColor: tokens.colorError500,
      boxShadow: `0 0 0 1px ${tokens.colorError500}`,
    },
  },
  triggerDisabled: {
    opacity: 0.4,
    backgroundColor: tokens.colorBgSubtle,
    cursor: 'not-allowed',
    boxShadow: 'none',
    ':hover': {
      borderColor: tokens.colorBorder,
    },
  },
  chevron: {
    width: tokens.spacing3,
    height: tokens.spacing3,
    color: tokens.colorFgSubtle,
    flexShrink: 0,
    marginInlineStart: tokens.spacing2,
  },
  popover: {
    borderRadius: tokens.radiusMd,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: tokens.colorBorder,
    backgroundColor: tokens.colorBgElevated,
    boxShadow: tokens.shadowMd,
    zIndex: tokens.zIndexDropdown,
    minWidth: 'var(--trigger-width)',
    maxHeight: '300px',
    overflowY: 'auto',
  },
  listbox: {
    padding: tokens.spacing1,
    outline: 'none',
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
  },
  item: {
    display: 'flex',
    alignItems: 'center',
    paddingBlock: tokens.spacing2,
    paddingInline: tokens.spacing3,
    borderRadius: tokens.radiusSm,
    color: tokens.colorFg,
    fontSize: tokens.fontSizeMd,
    lineHeight: tokens.lineHeightMd,
    cursor: 'pointer',
    outline: 'none',
    userSelect: 'none',
    backgroundColor: 'transparent',
    transitionProperty: 'background-color, color',
    transitionDuration: '0.1s',
    transitionTimingFunction: 'ease-in-out',
  },
  itemHovered: {
    backgroundColor: tokens.colorBgSubtle,
  },
  itemFocused: {
    backgroundColor: tokens.colorBgSubtle,
  },
  itemSelected: {
    backgroundColor: tokens.colorPrimary50,
    color: tokens.colorPrimary700,
    fontWeight: tokens.fontWeightMedium,
  },
  itemDisabled: {
    opacity: 0.4,
    cursor: 'not-allowed',
  },
  section: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
    paddingBlock: tokens.spacing1,
  },
  sectionHeader: {
    fontSize: tokens.fontSizeXs,
    fontWeight: tokens.fontWeightBold,
    color: tokens.colorFgSubtle,
    paddingBlock: tokens.spacing1,
    paddingInline: tokens.spacing3,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
})
