import * as stylex from '@stylexjs/stylex'
import { tokens } from '../../tokens/tokens.stylex'

export const styles = stylex.create({
  table: {
    borderCollapse: 'collapse',
    width: '100%',
    textAlign: 'start',
    fontFamily: tokens.fontFamilyBase,
    fontSize: tokens.fontSizeMd,
    lineHeight: tokens.lineHeightMd,
    color: tokens.colorFg,
  },
  header: {
    backgroundColor: tokens.colorBgSubtle,
    borderBottomWidth: '2px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorBorder,
  },
  headerSticky: {
    position: 'sticky',
    top: 0,
    zIndex: tokens.zIndexDropdown,
    backgroundColor: tokens.colorBgSubtle,
  },
  column: {
    paddingBlock: tokens.spacing3,
    paddingInline: tokens.spacing4,
    fontWeight: tokens.fontWeightSemibold,
    color: tokens.colorFg,
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorBorder,
    textAlign: 'start',
    outline: 'none',
    ':focus-visible': {
      outlineStyle: 'solid',
      outlineWidth: '2px',
      outlineOffset: '-2px',
      outlineColor: tokens.colorBorderFocus,
    },
  },
  columnSortable: {
    cursor: 'pointer',
    userSelect: 'none',
  },
  columnHovered: {
    backgroundColor: tokens.colorNeutral100,
  },
  columnContent: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: tokens.spacing2,
    width: '100%',
  },
  sortIndicator: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    color: tokens.colorFgSubtle,
    transitionProperty: 'color, transform',
    transitionDuration: '0.15s',
  },
  sortIndicatorActive: {
    color: tokens.colorPrimary500,
  },
  body: {
    outline: 'none',
  },
  row: {
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorBorder,
    backgroundColor: tokens.colorBg,
    outline: 'none',
    cursor: 'default',
    transitionProperty: 'background-color, color',
    transitionDuration: '0.15s',
    transitionTimingFunction: 'ease-in-out',
    '@media (prefers-reduced-motion: reduce)': {
      transitionProperty: 'none',
    },
  },
  rowHovered: {
    backgroundColor: tokens.colorBgSubtle,
  },
  rowSelected: {
    backgroundColor: tokens.colorPrimary50,
    color: tokens.colorPrimary700,
  },
  rowFocused: {
    outlineStyle: 'solid',
    outlineWidth: '2px',
    outlineOffset: '-2px',
    outlineColor: tokens.colorBorderFocus,
  },
  cell: {
    paddingBlock: tokens.spacing3,
    paddingInline: tokens.spacing4,
    color: 'inherit',
    outline: 'none',
    ':focus-visible': {
      outlineStyle: 'solid',
      outlineWidth: '2px',
      outlineOffset: '-2px',
      outlineColor: tokens.colorBorderFocus,
    },
  },
  emptyState: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    paddingBlock: tokens.spacing8,
    paddingInline: tokens.spacing4,
    textAlign: 'center',
    color: tokens.colorFgSubtle,
    width: '100%',
  },
  loadingState: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: tokens.spacing3,
    paddingBlock: tokens.spacing8,
    paddingInline: tokens.spacing4,
    textAlign: 'center',
    color: tokens.colorFgSubtle,
    width: '100%',
  },
})
